version: '3.8'  # docker-compose 파일 버전을 지정

services:
  web:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - type: bind
        source: .
        target: /code
      - /var/run/docker.sock:/var/run/docker.sock
