"""coin price to double

Revision ID: 30a7f1df4304
Revises: b16f941e6b3e
Create Date: 2024-08-31 20:43:56.833358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '30a7f1df4304'
down_revision: Union[str, None] = 'b16f941e6b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coin_price_history', 'price',
               existing_type=mysql.INTEGER(),
               type_=sa.Double(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coin_price_history', 'price',
               existing_type=sa.Double(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
