"""coin table name change

Revision ID: 93a9bdcef847
Revises: 56786b2b4e1d
Create Date: 2024-08-23 23:36:17.762556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '93a9bdcef847'
down_revision: Union[str, None] = '56786b2b4e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('korean_name', sa.String(length=200), nullable=False),
    sa.Column('english_name', sa.String(length=200), nullable=False),
    sa.Column('market_event_warning', sa.Boolean(), nullable=False),
    sa.Column('market_event_caution', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('english_name'),
    sa.UniqueConstraint('korean_name')
    )
    op.create_index(op.f('ix_coin_id'), 'coin', ['id'], unique=False)
    op.drop_index('english_name', table_name='coins')
    op.drop_index('ix_coins_id', table_name='coins')
    op.drop_index('korean_name', table_name='coins')
    op.drop_table('coins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('market', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('korean_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('english_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('market_event_warning', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('market_event_caution', mysql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('korean_name', 'coins', ['korean_name'], unique=True)
    op.create_index('ix_coins_id', 'coins', ['id'], unique=False)
    op.create_index('english_name', 'coins', ['english_name'], unique=True)
    op.drop_index(op.f('ix_coin_id'), table_name='coin')
    op.drop_table('coin')
    # ### end Alembic commands ###
