"""coin models

Revision ID: b16f941e6b3e
Revises: 93a9bdcef847
Create Date: 2024-08-30 23:07:27.209923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16f941e6b3e'
down_revision: Union[str, None] = '93a9bdcef847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_analysis_history',
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('coin_history_id', sa.Integer(), nullable=True),
    sa.Column('dopamine_index', sa.Double(), nullable=False),
    sa.Column('rsi', sa.Double(), nullable=False),
    sa.Column('macd', sa.Double(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_analysis_history_id'), 'coin_analysis_history', ['id'], unique=False)
    op.create_table('coin_price_history',
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('change', sa.Enum('EVEN', 'RISE', 'FALL', name='coinpricehistorychange'), nullable=False),
    sa.Column('change_price', sa.Double(), nullable=False),
    sa.Column('change_rate', sa.Double(), nullable=False),
    sa.Column('acc_trade_price_24h', sa.Double(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_price_history_id'), 'coin_price_history', ['id'], unique=False)
    op.add_column('coin', sa.Column('market_capitalization', sa.Integer(), nullable=True))
    op.add_column('coin', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('coin', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coin', 'updated_at')
    op.drop_column('coin', 'created_at')
    op.drop_column('coin', 'market_capitalization')
    op.drop_index(op.f('ix_coin_price_history_id'), table_name='coin_price_history')
    op.drop_table('coin_price_history')
    op.drop_index(op.f('ix_coin_analysis_history_id'), table_name='coin_analysis_history')
    op.drop_table('coin_analysis_history')
    # ### end Alembic commands ###
